language: erlang

notifications:
  disabled: true
sudo: required

script:
  - make rel
  - ./rel/riak_sets/bin/riak_sets start
  - sleep 5
  - ./rel/riak_sets/bin/riak_sets-admin ringready
  - make eunit
  - |
     if [ $TRAVIS_OTP_RELEASE == 17.4 ]
        then
          make dialyzer
        else
         true
     fi


otp_release:
   - 17.4
#   - 17.3
#   - 17.1
#   - 17.0
#   - R16B03-1
#   - R16B02
