language: erlang

notifications:
  disabled: true
sudo: required
install:
  -  git clone https://github.com/rebar/rebar3.git
  -  cd rebar3 
  - make
  - ./bootstrap/bootstrap
  -  export PATH=$PATH:.

script:
  - rebar3 get-deps
  - rebar3 compile
  - rebar3 eunit
  - |
     if [ $TRAVIS_OTP_RELEASE == 17.3 ]
        then
          make dialyzer
        else
         true
     fi



otp_release:
   - 17.4
otp_fake:
   - 17.5
   - 17.3
   - 17.2
   - 17.1
   - 17.0
   - R16B03-1
   - R16B02
   - R16B01